import java.util.Random;

class AutoGeneratedTrainer extends Trainer {

    AutoGeneratedTrainer () {
        this.generatedTrainer();
        AutoGeneratedMonster AGMonster = new AutoGeneratedMonster();
        AGMonster.generatedMonster();
    }

    private static String[] trainers = {
        "サトシ",
        "カスミ",
        "タケシ",
        "コジロウ",
        "ハルカ",
        "ムサシ",
        "セレナ",
        "N",
        "ヒカリ",
        "オーキド博士",
    };

    public void generatedTrainer () {
        int member = new Random().nextInt(11);
        setName(trainers[member]);
        System.out.println("おっと、 " + getName() + " が勝負を仕掛けてきた！");
        System.out.println("[トレーナー情報]");
        System.out.println("名前 : " + getName() + ", Level : " + getLevel());
    }
}
