import java.util.Random;

class AutoGeneratedMonster extends Monster {
    private static String[][] trainers = {
            {"ピカチュウ", "でんき", "10まんボルト", "でんこうせっか"},
            {"イーブイ", "ノーマル", "でんこうせっか", "とっておき"},
            {"カイリュー", "ドラゴン", "はかいこうせん", "りゅうのはどう"},
            {"リザードン", "ほのお", "だいもんじ", "オーバーヒート"},
            {"ルカリオ", "かくとう", "ラスターカノン", "インファイト"},
            {"ラプラス", "みず", "ハイドロポンプ", "ふぶき"},
            {"ミュウ", "エスパー", "ソーラービーム", "サイコキネシス"},
            {"ゲッコウガ", "みず", "ハイドロポンプ", "なみのり"},
            {"レックウザ", "ドラゴン", "げきりん", "ぼうふう"},
            {"カビゴン", "ノーマル", "ねむる", "ねごと"},
    };

    public void generatedMonster () {
        int member = new Random().nextInt(11);
        setName(trainers[member][0]);
        setAttribute(trainers[member][1]);
        this.setSkills(member);
        System.out.println("[ポケモン情報]");
        System.out.println("名前 : " + getName() + ", 属性 : " + getAttribute() + ", 技 : " + getSkills() + ", HP : " + getHp() + ", Level : " + getLevel());
        System.out.println();
        System.out.println("----------");
        System.out.println();
    }

    public void setSkills (int member) {
        for (int i = 2; i <=3; i++) {
            getSkills().add(trainers[member][i]);
        }
    }
}
