import java.util.Scanner;

class UseMonster {
    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);

        // Trainer インスタンス生成
        Trainer trainer = new Trainer();
        trainer.setInfo();
        trainer.printTrainer();

        // ライバルをランダム生成
        AutoGeneratedTrainer AGTrainer = new AutoGeneratedTrainer();

        // バトルインスタンス生成
        Battle battle = new Battle(trainer, AGTrainer);
        battle.battle();
    }
}
